# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hexo Blog Automation Deployment

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-dir: ./

        steps:
            -
                uses: actions/checkout@v3
                with:
                    submodules: recursive  # Fetch the theme
                    fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
            -
                uses: actions/setup-node@v3
                with:
                    node-version: "18.x"

            -
                name: Setup Deploy Private Key
                env:
                    HEXO_AUTO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_AUTO_DEPLOY_PRIVATE_KEY }}
                run: |
                    mkdir -p ~/.ssh/
                    echo "$HEXO_AUTO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
            -
                name: Setup Git Infomation
                run: |
                    git config --global user.name 'simple'
                    git config --global user.email '792378197@qq.com'
            -
                name: Setup Hexo Dependencies
                working-directory: ${{ env.working-dir }}
                run: |
                    npm install hexo-cli -g
                    npm install
            -
                name: Deploy Hexo
                working-directory: ${{ env.working-dir }}
                run: |
                    hexo clean
                    hexo g
                    hexo d